package render

import (
	"maps"
	"slices"
	"strings"

	md "github.com/nao1215/markdown"

	"github.com/davidcollom/awesomegen/internal/config"
	"github.com/davidcollom/awesomegen/internal/github"
)

const (
	TOCHeader = "Table of Contents"
)

func Markdown(list config.List) string {
	var buf strings.Builder
	doc := md.NewMarkdown(&buf)

	// Header
	doc.H1(list.Title).LF()
	// fmt.Fprintf(&b, "# %s\n\n", list.Title)
	if len(list.Badges) > 0 {
		for _, u := range list.Badges {
			doc.PlainTextf("![badge](%s)", u)
		}
		doc.LF()
	}
	if list.Tagline != "" {
		doc.Blockquote(list.Tagline).LF()
	}

	if list.GroupByTopic {
		writeByTopTags(doc, list)
	} else {
		writeFlatByTopic(doc, list)
	}

	doc.HorizontalRule()
	doc.PlainText("*Generated by [awesomegen](https://github.com/davidcollom/awesomegen).*")

	if err := doc.Build(); err != nil {
		return ""
	}

	return buf.String()
}

func writeByTopTags(doc *md.Markdown, list config.List) {
	var items []*config.Item
	for _, c := range list.Categories {
		items = append(items, c.Items...)
	}

	ranked := rankTopTags(items, list.TagAliases, list.MinTagCount, list.TopTagsLimit)
	if len(ranked) == 0 {
		doc.PlainText("_No topics found._")
		return
	}

	if list.TopicGroupingMode != nil && *list.TopicGroupingMode == config.TopicGroupingModeNested {
		nested := map[string]map[string][]*config.Item{}
		for _, it := range items {
			if it.GHMeta == nil {
				continue
			}
			p, s := primarySecondaryForRepo(it.GHMeta, ranked, list.TagAliases, list.TopicFallback)
			if _, ok := nested[p]; !ok {
				nested[p] = map[string][]*config.Item{}
			}
			nested[p][s] = append(nested[p][s], it)
		}

		// TOC
		prim := mapsSortedKeysNested(nested)
		doc.H2(TOCHeader).LF()
		for _, pk := range prim {
			doc.PlainTextf("- [%s](#%s)", TitlecaseKeys(pk, list.Locale), slug(pk))
		}
		doc.LF()

		for _, pk := range prim {
			doc.H3(TitlecaseKeys(pk, list.Locale)).LF()
			sec := nested[pk]
			sk := mapsSortedKeys(sec)
			for _, s := range sk {
				if s != list.TopicFallback || len(sec) > 1 {
					doc.H4(TitlecaseKeys(s, list.Locale)).LF()
				}
				writeRepoLines(doc, sec[s], list)
				doc.LF()
			}
		}
		return
	}

	// flat mode
	groups := map[string][]*config.Item{}
	for _, it := range items {
		if it.GHMeta == nil {
			continue
		}
		p, _ := primarySecondaryForRepo(it.GHMeta, ranked, list.TagAliases, list.TopicFallback)
		groups[p] = append(groups[p], it)
	}

	keys := mapsSortedKeys(groups)
	doc.H2(TOCHeader).LF()
	for _, k := range keys {
		doc.PlainTextf("- [%s](#%s)", TitlecaseKeys(k, list.Locale), slug(k))
	}
	doc.LF()

	for _, k := range keys {
		doc.H3(TitlecaseKeys(k, list.Locale)).LF()
		writeRepoLines(doc, groups[k], list)
		doc.LF()
	}
}

func writeFlatByTopic(doc *md.Markdown, list config.List) {
	groups := map[string][]*config.Item{}
	for _, c := range list.Categories {
		for _, it := range c.Items {
			if it.GHMeta == nil {
				continue
			}
			t := list.TopicFallback
			if len(it.GHMeta.Topics) > 0 && it.GHMeta.Topics[0] != "" {
				t = it.GHMeta.Topics[0]
			}
			groups[t] = append(groups[t], it)
		}
	}
	// TOC
	doc.H2(TOCHeader).LF()
	keys := mapsSortedKeys(groups)
	for _, k := range keys {
		doc.PlainTextf("- [%s](#%s)", k, slug(k))
	}
	doc.LF()

	// Sections
	for _, k := range keys {
		doc.H3(k).LF()
		writeRepoLines(doc, groups[k], list)
		doc.LF()
	}
}

func writeNestedByTopic(doc *md.Markdown, list config.List) {
	nested := map[string]map[string][]*config.Item{}
	for _, c := range list.Categories {
		for _, it := range c.Items {
			if it.GHMeta == nil {
				continue
			}
			topics := it.GHMeta.Topics
			primary := list.TopicFallback
			if len(topics) > 0 && topics[0] != "" {
				primary = topics[0]
			}
			secondary := list.TopicFallback
			if len(topics) > 1 && topics[1] != "" {
				secondary = topics[1]
			}

			if _, ok := nested[primary]; !ok {
				nested[primary] = map[string][]*config.Item{}
			}
			nested[primary][secondary] = append(nested[primary][secondary], it)
		}
	}

	// TOC (primary only to avoid clutter)
	doc.H2(TOCHeader).LF()
	primKeys := mapsSortedKeysNested(nested)
	for _, pk := range primKeys {
		doc.PlainTextf("- [%s](#%s)", pk, slug(pk))
	}
	doc.LF()

	for _, pk := range primKeys {
		doc.H3(pk).LF()
		sec := nested[pk]
		secKeys := mapsSortedKeys(sec)
		for _, sk := range secKeys {
			// Skip if primary==secondary and it would look redundant? Keep simple for now.
			doc.H4(sk).LF()
			writeRepoLines(doc, sec[sk], list)
		}
	}
}

func writeFlatUnGrouped(doc *md.Markdown, list config.List) {
	doc.H2("Repositories").LF()
	if len(list.Categories) == 0 {
		return
	}
	writeRepoLines(doc, list.Categories[0].Items, list)
	doc.LF()
}

func writeRepoLines(doc *md.Markdown, items []*config.Item, list config.List) {
	// keep sort stable & readable
	slices.SortFunc(items, func(a, b *config.Item) int {
		var ak, bk string
		if a.GHMeta != nil {
			ak = a.GHMeta.FullName
		}
		if b.GHMeta != nil {
			bk = b.GHMeta.FullName
		}
		switch {
		case ak < bk:
			return -1
		case ak > bk:
			return 1
		default:
			return 0
		}
	})
	for _, it := range items {
		m := it.GHMeta
		if m == nil {
			continue
		}
		// stars (humanised, optional)
		stars := humanStars(m.Stars, *list.StarsFormat, list.Locale)
		starPart := ""
		if stars != "" {
			starPart = " — ⭐ " + stars
		}

		license := ""
		if m.License != "" {
			license = " · " + m.License
		}

		note := ""
		if it.Notes != "" {
			note = " — " + it.Notes
		}

		desc := strings.TrimSpace(m.Description)
		doc.PlainTextf("- [%s](%s)%s%s — %s%s",
			m.FullName, m.URL, starPart, license, desc, note)
	}
}

func mapsSortedKeys[T any](m map[string]T) []string {
	keys := slices.Collect(maps.Keys(m))
	slices.Sort(keys)
	return keys
}

func mapsSortedKeysNested(m map[string]map[string][]*config.Item) []string {
	keys := slices.Collect(maps.Keys(m))
	slices.Sort(keys)
	return keys
}

func primarySecondaryForRepo(m *github.RepoMeta, ranked []string, aliases map[string]string, fallback string) (string, string) {
	if m == nil {
		return fallback, fallback
	}
	// Build the set of this repo's canonical tags
	rtags := make([]string, 0, len(m.Topics))
	seen := map[string]struct{}{}
	for _, raw := range m.Topics {
		t := canonicalTag(raw, aliases)
		if t == "" {
			continue
		}
		if _, ok := seen[t]; ok {
			continue
		}
		seen[t] = struct{}{}
		rtags = append(rtags, t)
	}
	// primary = first tag that appears in ranked order
	primary := fallback
	for _, t := range ranked {
		for _, rt := range rtags {
			if rt == t {
				primary = t
				goto foundPrimary
			}
		}
	}
foundPrimary:
	// secondary = next ranked tag (distinct), else fallback
	secondary := fallback
	if primary != fallback {
		for _, t := range ranked {
			if t == primary {
				continue
			}
			for _, rt := range rtags {
				if rt == t {
					secondary = t
					goto foundSecondary
				}
			}
		}
	}
foundSecondary:
	return primary, secondary
}
